FROM jenkins/ssh-agent:latest

USER root

# Actualizare și instalare pachete
RUN apt-get update && apt-get install -y \
    php-cli \
    php-mbstring \
    php-xml \
    php-curl \
    git \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Instalare Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Verificare instalări
RUN php --version && composer --version

USER jenkins

WORKDIR /home/jenkins